- name: Install GitHub on Ubuntu and Start the Backend
  become: yes
  tasks:
    - name: Ensure Git is installed
      apt:
        name: git
        state: present

    - name: Check Git version
      shell: git -v
      register: git_version_output

    - name: Clone Repository
      shell: git clone https://github.com/SachsAlex/casino-backend.git

    - name: Move to Repository
      shell: cd ./casino-backend

    - name: Show Content
      shell: ls -a

    # - name: Install Node.js dependencies
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - curl
    #     - software-properties-common

    # - name: Add NodeSource repository
    #   apt_repository:
    #     repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
    #     state: present
    #     update_cache: yes
    #     filename: nodesource

    # - name: Install Node.js
    #   apt:
    #     name: nodejs
    #     state: present

    # - name: npm install
    #   shell: npm install

    # - name: Run Backend
    #   shell: npm run dev
