- name: Install GitHub on Ubuntu and Start the Backend
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure Git is installed
      apt:
        name: git
        state: present

    - name: Check Git version
      shell: git -v
      register: git_version_output

    - name: Add NodeSource key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource Repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main
        state: present

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install npm
      apt:
        name: npm
        state: present

    # - name: Install Node.js
    #   apt:
    #     name: nodejs
    #     state: present

    # - name: Install Node.js
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: "20"

    - name: Check Node version
      shell: node -v
      register: node_version_output

    - name: Clone Repository
      shell: git clone https://github.com/SachsAlex/casino-backend.git

    - name: Move to Repository
      shell: cd ./casino-backend

    - name: npm install
      shell: npm install

    - name: Run Backend
      shell: npm run dev
